# Generated by Django 4.0 on 2022-01-25 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_project_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stat',
        ),
    ]
